// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using controle_estoque_cshap.Data;

#nullable disable

namespace controle_estoque_cshap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [ExcludeFromCodeCoverage]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("controle_estoque_cshap.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("PRIMARY");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.EfmigrationsHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__EFMigrationsHistory", (string)null);
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)")
                        .HasColumnName("batch");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductId" }, "fk_item_product");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Movement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("movement_id");

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int")
                        .HasColumnName("new_quantity");

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("int")
                        .HasColumnName("previous_quantity");

                    b.Property<int>("QuantityMoved")
                        .HasColumnType("int")
                        .HasColumnName("quantity_moved");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MovementId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ItemId" }, "fk_movement_item");

                    b.HasIndex(new[] { "UserId" }, "fk_movement_user");

                    b.ToTable("movement", (string)null);
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("MinimumQuantity")
                        .HasColumnType("int")
                        .HasColumnName("minimum_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("sku");

                    b.Property<sbyte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'");

                    b.HasKey("ProductId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "fk_product_category");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("profile");

                    b.HasKey("IdUser")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Item", b =>
                {
                    b.HasOne("controle_estoque_cshap.Models.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_item_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Movement", b =>
                {
                    b.HasOne("controle_estoque_cshap.Models.Item", "Item")
                        .WithMany("Movements")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("fk_movement_item");

                    b.HasOne("controle_estoque_cshap.Models.User", "User")
                        .WithMany("Movements")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_movement_user");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Product", b =>
                {
                    b.HasOne("controle_estoque_cshap.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("fk_product_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Item", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.Product", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("controle_estoque_cshap.Models.User", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
